apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.auditService.replicas }}
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: {{ .Values.auditService.image }}
          imagePullPolicy: {{ .Values.auditService.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.auditService.port }}
          envFrom:
            - configMapRef:
                name: audit-service-config
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.auditService.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.auditService.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
