apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
data:
  01_extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS vector;
    CREATE EXTENSION IF NOT EXISTS timescaledb;
    CREATE EXTENSION IF NOT EXISTS age;
    LOAD 'age';
    SET search_path = ag_catalog, "$user", public;
    CREATE DATABASE zitadel;
