apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
data:
  WELLBE_LOG_LEVEL: {{ .Values.api.config.logLevel | quote }}
  WELLBE_ENVIRONMENT: {{ .Values.api.config.environment | quote }}
