apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-writer-config
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
data:
  WELLBE_DATABASE_URL: {{ include "wellbe-local.databaseUrlAsync" . | quote }}
  WELLBE_S3_ENDPOINT: {{ .Values.vaultWriter.config.s3Endpoint | quote }}
  WELLBE_S3_ACCESS_KEY: {{ .Values.vaultWriter.config.s3AccessKey | quote }}
  WELLBE_S3_SECRET_KEY: {{ .Values.vaultWriter.config.s3SecretKey | quote }}
  WELLBE_S3_BUCKET_RAW: {{ .Values.vaultWriter.config.s3BucketRaw | quote }}
  WELLBE_S3_OBJECT_LOCK_RETENTION_DAYS: {{ .Values.vaultWriter.config.s3ObjectLockRetentionDays | quote }}
  WELLBE_REDIS_URL: {{ .Values.vaultWriter.config.redisUrl | quote }}
  WELLBE_LOG_LEVEL: {{ .Values.vaultWriter.config.logLevel | quote }}
  WELLBE_ENVIRONMENT: {{ .Values.vaultWriter.config.environment | quote }}
