apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-service-config
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
data:
  WELLBE_LOG_LEVEL: {{ .Values.auditService.config.logLevel | quote }}
  WELLBE_ENVIRONMENT: {{ .Values.auditService.config.environment | quote }}
