apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-worker
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ingestionWorker.replicas }}
  selector:
    matchLabels:
      app: ingestion-worker
  template:
    metadata:
      labels:
        app: ingestion-worker
    spec:
      containers:
        - name: ingestion-worker
          image: {{ .Values.ingestionWorker.image }}
          imagePullPolicy: {{ .Values.ingestionWorker.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.ingestionWorker.port }}
          envFrom:
            - configMapRef:
                name: ingestion-worker-config
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ingestionWorker.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.ingestionWorker.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
