apiVersion: v1
kind: Service
metadata:
  name: processing-worker
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: processing-worker
  ports:
    - port: {{ .Values.processingWorker.port }}
      targetPort: {{ .Values.processingWorker.port }}
