apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-worker
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.processingWorker.replicas }}
  selector:
    matchLabels:
      app: processing-worker
  template:
    metadata:
      labels:
        app: processing-worker
    spec:
      containers:
        - name: processing-worker
          image: {{ .Values.processingWorker.image }}
          imagePullPolicy: {{ .Values.processingWorker.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.processingWorker.port }}
          envFrom:
            - configMapRef:
                name: processing-worker-config
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.processingWorker.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.processingWorker.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
