apiVersion: v1
kind: Service
metadata:
  name: safety-gate
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: safety-gate
  ports:
    - port: {{ .Values.safetyGate.port }}
      targetPort: {{ .Values.safetyGate.port }}
