apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-writer
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vaultWriter.replicas }}
  selector:
    matchLabels:
      app: vault-writer
  template:
    metadata:
      labels:
        app: vault-writer
    spec:
      containers:
        - name: vault-writer
          image: {{ .Values.vaultWriter.image }}
          imagePullPolicy: {{ .Values.vaultWriter.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.vaultWriter.port }}
          envFrom:
            - configMapRef:
                name: vault-writer-config
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.vaultWriter.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.vaultWriter.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
