apiVersion: apps/v1
kind: Deployment
metadata:
  name: zitadel
  labels:
    {{- include "wellbe-local.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zitadel
  template:
    metadata:
      labels:
        app: zitadel
    spec:
      enableServiceLinks: false
      containers:
        - name: zitadel
          image: {{ .Values.zitadel.image }}
          args:
            - start-from-init
            - --masterkey
            - {{ .Values.zitadel.masterkey | quote }}
            - --tlsMode
            - disabled
          env:
            - name: ZITADEL_DATABASE_POSTGRES_HOST
              value: "wellbe-postgres"
            - name: ZITADEL_DATABASE_POSTGRES_PORT
              value: "5432"
            - name: ZITADEL_DATABASE_POSTGRES_DATABASE
              value: "zitadel"
            - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
              value: {{ .Values.postgres.user | quote }}
            - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE
              value: "disable"
            - name: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
              value: {{ .Values.postgres.user | quote }}
            - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
              value: {{ .Values.postgres.password | quote }}
            - name: ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE
              value: "disable"
            - name: ZITADEL_EXTERNALSECURE
              value: "false"
            - name: ZITADEL_EXTERNALPORT
              value: {{ .Values.zitadel.externalPort | quote }}
            - name: ZITADEL_EXTERNALDOMAIN
              value: {{ .Values.zitadel.externalDomain | quote }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /debug/ready
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /debug/healthz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
