FROM python:3.13-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app/db

COPY db/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY db/alembic.ini ./alembic.ini
COPY db/migrations/ ./migrations/

CMD ["alembic", "upgrade", "head"]
