/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Threads */
        get: operations["list_threads_v1_threads_get"];
        put?: never;
        /** Create Thread */
        post: operations["create_thread_v1_threads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_v1_threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/threads/{thread_id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition Thread */
        post: operations["transition_thread_v1_threads__thread_id__transition_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/access/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Access Evaluate */
        post: operations["access_evaluate_v2_access_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/audit/my-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Audit Events */
        get: operations["my_audit_events_v2_audit_my_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Corrections */
        get: operations["list_corrections_v2_corrections_get"];
        put?: never;
        /** Request Correction */
        post: operations["request_correction_v2_corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Grants */
        get: operations["list_grants_v2_grants_get"];
        put?: never;
        /** Create Grant */
        post: operations["create_grant_v2_grants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/grants/{grant_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Grant */
        post: operations["revoke_grant_v2_grants__grant_id__revoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/investigations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Investigations */
        get: operations["list_investigations_v2_investigations_get"];
        put?: never;
        /** Create Investigation */
        post: operations["create_investigation_v2_investigations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/investigations/{investigation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Investigation */
        get: operations["get_investigation_v2_investigations__investigation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Investigation */
        patch: operations["patch_investigation_v2_investigations__investigation_id__patch"];
        trace?: never;
    };
    "/v2/investigations/{investigation_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Investigation */
        post: operations["close_investigation_v2_investigations__investigation_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/investigations/{investigation_id}/external-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Investigation External Context */
        get: operations["investigation_external_context_v2_investigations__investigation_id__external_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/investigations/{investigation_id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reopen Investigation */
        post: operations["reopen_investigation_v2_investigations__investigation_id__reopen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/investigations/{investigation_id}/theories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Theories */
        get: operations["list_theories_v2_investigations__investigation_id__theories_get"];
        put?: never;
        /** Create Theory */
        post: operations["create_theory_v2_investigations__investigation_id__theories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/pending-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Items */
        get: operations["list_pending_items_v2_pending_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/render/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** V2 Render Validate */
        post: operations["v2_render_validate_v2_render_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** V2 Schema */
        get: operations["v2_schema_v2_schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/threads/{thread_id}/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thread Memories */
        get: operations["thread_memories_v2_threads__thread_id__memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workspaces */
        get: operations["list_workspaces_v2_workspaces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_v2_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccessEvaluateRequest */
        AccessEvaluateRequest: {
            /** Action */
            action: string;
            /**
             * Purpose Code
             * @default personal_care
             */
            purpose_code: string;
            /** Resource Id */
            resource_id?: string | null;
            /** Resource Type */
            resource_type: string;
        };
        /** AccessPredicateV2 */
        AccessPredicateV2: {
            /** Access Predicate Hash */
            access_predicate_hash: string;
            /** Audit Event Id */
            audit_event_id: string;
            /** Capabilities */
            capabilities?: {
                [key: string]: unknown;
            };
            /**
             * Decision
             * @enum {string}
             */
            decision: "allow" | "deny" | "allow_with_obligations";
            /** Decision Reason Codes */
            decision_reason_codes?: string[];
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
            /** Grant Id */
            grant_id?: string | null;
            /** Obligations */
            obligations?: string[];
            /** Policy Version */
            policy_version: string;
            /** Purpose Code */
            purpose_code: string;
            /** Resource Constraints Summary */
            resource_constraints_summary?: string | null;
            /** Role Binding Id */
            role_binding_id?: string | null;
            /**
             * Schema Version
             * @default c13.access_predicate.v2
             * @constant
             */
            schema_version: "c13.access_predicate.v2";
            /** Scope Codes */
            scope_codes?: string[];
            /**
             * Valid Until
             * Format: date-time
             */
            valid_until: string;
            /** Workspace Id */
            workspace_id?: string | null;
        };
        /** AuditRefV2 */
        AuditRefV2: {
            /** Audit Event Id */
            audit_event_id: string;
            /** Correlation Id */
            correlation_id: string;
            /** Event Summary */
            event_summary: string;
            /**
             * Schema Version
             * @default c13.audit_ref.v2
             * @constant
             */
            schema_version: "c13.audit_ref.v2";
            /** Trace Id */
            trace_id?: string | null;
            /** Visibility */
            visibility: string[];
        };
        /** C10ObligationV2 */
        C10ObligationV2: {
            /**
             * Blocking If Unfulfilled
             * @default true
             */
            blocking_if_unfulfilled: boolean;
            /**
             * Display Location
             * @default inline
             * @enum {string}
             */
            display_location: "inline" | "banner" | "source_panel";
            /** Obligation Code */
            obligation_code: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /**
             * Schema Version
             * @default c13.c10_obligation.v2
             * @constant
             */
            schema_version: "c13.c10_obligation.v2";
        };
        /** CloseInvestigationRequest */
        CloseInvestigationRequest: {
            /** Expected Version */
            expected_version?: number | null;
            /**
             * Reason Code
             * @default user_closed
             */
            reason_code: string;
        };
        /**
         * CorrectionTargetKind
         * @enum {string}
         */
        CorrectionTargetKind: "c2_raw_event" | "c4_extracted_fact" | "c5_evidence_link" | "c6_kg_node" | "c6_kg_edge" | "c7_thread_label" | "c8_memory_entry" | "c9_pending_item" | "c14_investigation" | "c15_theory";
        /** CorrectionTargetRequest */
        CorrectionTargetRequest: {
            /** Base Value Hash */
            base_value_hash?: string | null;
            /** Field Path */
            field_path?: string | null;
            /** Proposed Value Hash */
            proposed_value_hash?: string | null;
            /**
             * Semantic Rank
             * @default 50
             */
            semantic_rank: number;
            /**
             * Target Id
             * Format: uuid
             */
            target_id: string;
            target_kind: components["schemas"]["CorrectionTargetKind"];
            /** Target Version */
            target_version?: string | null;
        };
        /** CorrectionTargetV2 */
        CorrectionTargetV2: {
            /** Field Path */
            field_path?: string | null;
            /** Semantic Rank */
            semantic_rank?: number | null;
            /** Target Id */
            target_id: string;
            /** Target Kind */
            target_kind: string;
        };
        /**
         * CorrectionType
         * @enum {string}
         */
        CorrectionType: "replace_value" | "mark_incorrect" | "add_missing_context" | "mark_stale" | "withdraw_from_current_view" | "relabel_thread" | "merge_duplicate" | "split_context" | "change_evidence_weight";
        /** CorrectionV2 */
        CorrectionV2: {
            /** Actor Authority */
            actor_authority: string;
            /** Applied At */
            applied_at?: string | null;
            /** Audit Refs */
            audit_refs?: components["schemas"]["AuditRefV2"][];
            /** Correction Id */
            correction_id: string;
            /** Correction Type */
            correction_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Effective At */
            effective_at?: string | null;
            /** Rationale */
            rationale?: string | null;
            /**
             * Schema Version
             * @default c13.correction.v2
             * @constant
             */
            schema_version: "c13.correction.v2";
            /** Status */
            status: string;
            /** Targets */
            targets?: components["schemas"]["CorrectionTargetV2"][];
        };
        /** CreateGrantRequest */
        CreateGrantRequest: {
            /** Actions */
            actions?: string[];
            /** Data Categories */
            data_categories?: string[];
            /** Expires At */
            expires_at?: string | null;
            /** Grantee Type */
            grantee_type: string;
            /** Grantee User Id */
            grantee_user_id?: string | null;
            /** Purpose */
            purpose?: string | null;
            /** Thread Ids */
            thread_ids?: string[];
        };
        /** CreateInvestigationRequest */
        CreateInvestigationRequest: {
            /** @default user */
            owner_type: components["schemas"]["InvestigationOwnerType"];
            /** Primary Question */
            primary_question: string;
            /** Thread Ids */
            thread_ids?: string[];
        };
        /** CreateTheoryRequest */
        CreateTheoryRequest: {
            /** Theory Text */
            theory_text: string;
            /** @default symptom_cause */
            theory_type: components["schemas"]["TheoryType"];
        };
        /** CreateThreadRequest */
        CreateThreadRequest: {
            /** Title */
            title: string;
        };
        /** GrantCapabilitiesV2 */
        GrantCapabilitiesV2: {
            /**
             * Can Comment
             * @default false
             */
            can_comment: boolean;
            /**
             * Can Contribute
             * @default false
             */
            can_contribute: boolean;
            /**
             * Can Export
             * @default false
             */
            can_export: boolean;
            /**
             * Can Invite
             * @default false
             */
            can_invite: boolean;
            /**
             * Can Read
             * @default false
             */
            can_read: boolean;
            /**
             * Can Request Correction
             * @default false
             */
            can_request_correction: boolean;
            /**
             * Can Run Aggregate
             * @default false
             */
            can_run_aggregate: boolean;
            /**
             * Can Search
             * @default false
             */
            can_search: boolean;
            /**
             * Can Use Research Sandbox
             * @default false
             */
            can_use_research_sandbox: boolean;
            /**
             * Can View External Context
             * @default false
             */
            can_view_external_context: boolean;
        };
        /** GrantV2 */
        GrantV2: {
            /** Audit Refs */
            audit_refs?: components["schemas"]["AuditRefV2"][];
            capabilities?: components["schemas"]["GrantCapabilitiesV2"];
            /** Contribution Policy */
            contribution_policy?: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Expires At */
            expires_at?: string | null;
            /** Grant Id */
            grant_id: string;
            /** Grant Type */
            grant_type: string;
            /** Grantee Ref */
            grantee_ref: string;
            /** Obligations */
            obligations?: string[];
            /** Purpose Code */
            purpose_code: string;
            /** Resource Constraints Summary */
            resource_constraints_summary: string;
            /** Revoked At */
            revoked_at?: string | null;
            /** Role Binding Id */
            role_binding_id: string;
            /**
             * Schema Version
             * @default c13.grant.v2
             * @constant
             */
            schema_version: "c13.grant.v2";
            /** Scope Codes */
            scope_codes: string[];
            /** Scope Profile Version */
            scope_profile_version: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Status */
            status: string;
            /** Subject Ref */
            subject_ref: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthThreadStatus
         * @description Lifecycle states for a Health Thread.
         *
         *     Defined in docs/system-design/health_thread_state_machine.md.
         * @enum {string}
         */
        HealthThreadStatus: "draft" | "active_unresolved" | "waiting_for_result" | "referred" | "watchful_waiting" | "escalated" | "explained" | "chronic_monitoring" | "closed" | "reopened" | "archived";
        /**
         * InvestigationOwnerType
         * @enum {string}
         */
        InvestigationOwnerType: "user" | "caregiver" | "system";
        /**
         * InvestigationStatus
         * @description Workflow status (NEVER a clinical conclusion — constraint G1).
         * @enum {string}
         */
        InvestigationStatus: "open" | "monitoring" | "waiting_for_data" | "ready_for_visit" | "handed_off" | "closed";
        /** InvestigationV2 */
        InvestigationV2: {
            /** Audit Refs */
            audit_refs?: components["schemas"]["AuditRefV2"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Created By */
            created_by: {
                [key: string]: unknown;
            };
            /** Evidence Bundle Ref */
            evidence_bundle_ref: string;
            /** External Context Refs */
            external_context_refs?: string[];
            /** Health Thread Ids */
            health_thread_ids: string[];
            /** Investigation Id */
            investigation_id: string;
            /** Linked Theory Ids */
            linked_theory_ids?: string[];
            /** Missing Context Items */
            missing_context_items?: {
                [key: string]: unknown;
            }[];
            /** Participants */
            participants?: {
                [key: string]: unknown;
            }[];
            /** Pending Items */
            pending_items?: {
                [key: string]: unknown;
            }[];
            /** Primary Question */
            primary_question: string;
            /** Review Cadence */
            review_cadence?: {
                [key: string]: unknown;
            } | null;
            /** Safety Level */
            safety_level: string;
            /**
             * Schema Version
             * @default c13.investigation.v2
             * @constant
             */
            schema_version: "c13.investigation.v2";
            /** Scope */
            scope: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workspace Id */
            workspace_id: string;
        };
        /** MemoryEntryV2 */
        MemoryEntryV2: {
            /** Audit Refs */
            audit_refs?: components["schemas"]["AuditRefV2"][];
            /** Lifecycle State */
            lifecycle_state: string;
            /** Memory Entry Id */
            memory_entry_id: string;
            /** Memory Type */
            memory_type: string;
            /**
             * Projection Stale
             * @default false
             */
            projection_stale: boolean;
            /** Resolved Overlays */
            resolved_overlays?: {
                [key: string]: unknown;
            }[];
            /**
             * Schema Version
             * @default c13.memory_entry.v2
             * @constant
             */
            schema_version: "c13.memory_entry.v2";
            /** Source Refs */
            source_refs?: {
                [key: string]: unknown;
            }[];
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string;
        };
        /** PendingItemV2 */
        PendingItemV2: {
            /** Audit Refs */
            audit_refs?: components["schemas"]["AuditRefV2"][];
            /**
             * Blocks Closure
             * @default false
             */
            blocks_closure: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Due At */
            due_at?: string | null;
            /**
             * Due Precision
             * @default unknown
             */
            due_precision: string;
            /** Investigation Ids */
            investigation_ids?: string[];
            /** Item Type */
            item_type: string;
            /** Next Action Code */
            next_action_code?: string | null;
            /** Pending Item Id */
            pending_item_id: string;
            /** Primary Thread Id */
            primary_thread_id: string;
            /**
             * Schema Version
             * @default c13.pending_item.v2
             * @constant
             */
            schema_version: "c13.pending_item.v2";
            /** Status */
            status: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RelevanceLinkV2 */
        RelevanceLinkV2: {
            /** Audit Refs */
            audit_refs?: components["schemas"]["AuditRefV2"][];
            /**
             * Context Only
             * @constant
             */
            context_only: true;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Evaluated At
             * Format: date-time
             */
            evaluated_at: string;
            /** External Claim Id */
            external_claim_id: string;
            /** External Source Id */
            external_source_id: string;
            /** Linked Investigation Id */
            linked_investigation_id: string;
            /** Linked Thread Id */
            linked_thread_id: string;
            /**
             * Not Personal Evidence
             * @constant
             */
            not_personal_evidence: true;
            /** Obligations */
            obligations?: string[];
            /** Relevance Link Id */
            relevance_link_id: string;
            /** Relevance Status */
            relevance_status: string;
            /**
             * Schema Version
             * @default c13.relevance_link.v2
             * @constant
             */
            schema_version: "c13.relevance_link.v2";
            source_quality_tier: components["schemas"]["SourceQualityTierV2"];
            /** Why Relevant Summary */
            why_relevant_summary: string;
        };
        /** RenderApprovalV2 */
        RenderApprovalV2: {
            /** Audit Event Id */
            audit_event_id: string;
            /** Binds Request Id */
            binds_request_id: string;
            /** Binds Text Sha256 */
            binds_text_sha256: string;
            /** C10 Decision */
            c10_decision: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Obligations */
            obligations?: components["schemas"]["C10ObligationV2"][];
            /** Reason Codes */
            reason_codes?: string[];
            /** Render Authorization Ref */
            render_authorization_ref: string;
            /** Render Token */
            render_token?: string | null;
            /** Review Markers */
            review_markers?: string[];
            /**
             * Schema Version
             * @default c13.render_approval.v2
             * @constant
             */
            schema_version: "c13.render_approval.v2";
            /** Source Display Requirements */
            source_display_requirements?: string[];
        };
        /** RenderValidateRequestV2 */
        RenderValidateRequestV2: {
            /**
             * Correlation Id
             * @default corr-render
             */
            correlation_id: string;
            render_approval?: components["schemas"]["RenderApprovalV2"] | null;
            /**
             * Schema Version
             * @default c13.render_validate.request.v2
             * @constant
             */
            schema_version: "c13.render_validate.request.v2";
            /** Surface Capabilities */
            surface_capabilities?: string[];
            /** Text */
            text: string;
        };
        /** RequestCorrectionRequest */
        RequestCorrectionRequest: {
            correction_type: components["schemas"]["CorrectionType"];
            /** Proposed Payload */
            proposed_payload?: {
                [key: string]: unknown;
            } | null;
            /** Rationale */
            rationale?: string | null;
            /**
             * Raw Correction Event Id
             * Format: uuid
             */
            raw_correction_event_id: string;
            target: components["schemas"]["CorrectionTargetRequest"];
        };
        /** RevokeGrantRequest */
        RevokeGrantRequest: {
            /**
             * Reason
             * @default user_revoked
             */
            reason: string;
        };
        /**
         * SourceQualityTierV2
         * @enum {string}
         */
        SourceQualityTierV2: "tier_1" | "tier_2" | "tier_3" | "tier_4" | "tier_5";
        /** SupportedSchemaVersionsV2 */
        SupportedSchemaVersionsV2: {
            /**
             * Schema Version
             * @default c13.schema_versions.v2
             * @constant
             */
            schema_version: "c13.schema_versions.v2";
            /** Supported Schema Versions */
            supported_schema_versions?: string[];
        };
        /**
         * TheoryType
         * @enum {string}
         */
        TheoryType: "symptom_cause" | "treatment_effect" | "trigger" | "pattern" | "other";
        /** TheoryV2 */
        TheoryV2: {
            /** Audit Refs */
            audit_refs?: components["schemas"]["AuditRefV2"][];
            /** Clinician Annotation Ref */
            clinician_annotation_ref?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Evidence Against */
            evidence_against?: {
                [key: string]: unknown;
            }[];
            /** Evidence For */
            evidence_for?: {
                [key: string]: unknown;
            }[];
            /** External Context Refs */
            external_context_refs?: string[];
            /** Health Thread Id */
            health_thread_id: string;
            /** Investigation Id */
            investigation_id: string;
            /** Label */
            label: string;
            /** Missing Data */
            missing_data?: {
                [key: string]: unknown;
            }[];
            /**
             * Not Diagnosis
             * @constant
             */
            not_diagnosis: true;
            /** Proposed By */
            proposed_by: {
                [key: string]: unknown;
            };
            /** Review Marker */
            review_marker?: string | null;
            /** Safety Level */
            safety_level: string;
            /**
             * Schema Version
             * @default c13.theory.v2
             * @constant
             */
            schema_version: "c13.theory.v2";
            /** Status */
            status: string;
            /** Theory Id */
            theory_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ThreadV1 */
        ThreadV1: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Patient Id */
            patient_id: string;
            /**
             * Schema Version
             * @default c13.health_thread.v1
             */
            schema_version: string;
            /** Status */
            status: string;
            /** Status Version */
            status_version: number;
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TransitionInvestigationRequest */
        TransitionInvestigationRequest: {
            /** Expected Version */
            expected_version?: number | null;
            /** Reason Code */
            reason_code: string;
            target_status: components["schemas"]["InvestigationStatus"];
        };
        /** TransitionThreadRequest */
        TransitionThreadRequest: {
            /** Expected Version */
            expected_version?: number | null;
            /** Reason Code */
            reason_code: string;
            target_status: components["schemas"]["HealthThreadStatus"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceV2 */
        WorkspaceV2: {
            /** Active Role Binding */
            active_role_binding?: {
                [key: string]: unknown;
            } | null;
            /** Audit Refs */
            audit_refs?: components["schemas"]["AuditRefV2"][];
            /** Capability Summary */
            capability_summary?: {
                [key: string]: unknown;
            };
            /** Controller Subject Ref */
            controller_subject_ref: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Data Access Not Implied
             * @constant
             */
            data_access_not_implied: true;
            /** Display Name */
            display_name: string;
            /** Membership State */
            membership_state: string;
            /**
             * Schema Version
             * @default c13.workspace.v2
             * @constant
             */
            schema_version: "c13.workspace.v2";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Workspace Id */
            workspace_id: string;
            /** Workspace Type */
            workspace_type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_threads_v1_threads_get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadV1"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_thread_v1_threads_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThreadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thread_v1_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transition_thread_v1_threads__thread_id__transition_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionThreadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    access_evaluate_v2_access_evaluate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccessEvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessPredicateV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_audit_events_v2_audit_my_events_get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRefV2"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_corrections_v2_corrections_get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionV2"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_correction_v2_corrections_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrectionV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_grants_v2_grants_get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantV2"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_grant_v2_grants_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_grant_v2_grants__grant_id__revoke_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                grant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeGrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_investigations_v2_investigations_get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationV2"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_investigation_v2_investigations_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInvestigationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_investigation_v2_investigations__investigation_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_investigation_v2_investigations__investigation_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionInvestigationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_investigation_v2_investigations__investigation_id__close_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseInvestigationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    investigation_external_context_v2_investigations__investigation_id__external_context_get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelevanceLinkV2"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reopen_investigation_v2_investigations__investigation_id__reopen_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CloseInvestigationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvestigationV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_theories_v2_investigations__investigation_id__theories_get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TheoryV2"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_theory_v2_investigations__investigation_id__theories_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                investigation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTheoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TheoryV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_items_v2_pending_items_get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingItemV2"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v2_render_validate_v2_render_validate_post: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderValidateRequestV2"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    v2_schema_v2_schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupportedSchemaVersionsV2"];
                };
            };
        };
    };
    thread_memories_v2_threads__thread_id__memories_get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryEntryV2"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_workspaces_v2_workspaces_get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceV2"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_v2_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-wellbe-actor-id"?: string | null;
                "x-wellbe-patient-id"?: string | null;
                "x-wellbe-actor-type"?: string;
                "x-correlation-id"?: string | null;
                "x-trace-id"?: string | null;
            };
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
