/**
 * WellBe API Client
 * Auto-generated from contracts/openapi/wellbe.openapi.json
 * Do not edit this file manually — run `npm run generate` to regenerate.
 */

export {};  // stub — generated types will be exported here
